---
driver:
  name: vagrant
driver_config:
  customize:
    memory: 1024

platforms:
  - name: ubuntu-12.04

suites:
- name: default
  run_list:
    - "recipe[apt]"
    - "recipe[rubycas::server]"
    - "recipe[rubycas::database]"
    - "recipe[rubycas::nginx]"
  attributes:
    mysql:
      server_root_password: 'rootpass'
      server_debian_password: 'debpass'
      server_repl_password: 'replpass'
- name: postgresdb
  data_bags_path: "test/integration/postgresdb/data_bags"
  run_list:
    - "recipe[apt]"
    - "recipe[rubycas::database]"
  attributes:
    rubycas:
      database:
        data_bag_item: 'rubycas'
        data_bag_item: 'postgres_database'
    postgresql:
      password:
        postgres: '123456'
